default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  adapter: sqlite3
  encoding: utf8
  database: /db/development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: /db/test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: /db/shop-it
  pool: 5
  username: shop-it
  password: <%= ENV['SHOP-IT_DATABASE_PASSWORD'] %>
